In [1]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [2]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 69d1446bfc5da80adcd802f8, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>

In [3]:
db = client['loja']
colecao = db['vendas']

In [4]:
dados = [
    {
        "cliente": "Ana",
        "produto": "Mouse",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 50,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 1),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Bruno",
        "produto": "Teclado",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 120,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Carla",
        "produto": "Caderno",
        "categoria": "Papelaria",
        "quantidade": 5,
        "preco_unitario": 15,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 2),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "Daniel",
        "produto": "Caneta",
        "categoria": "Papelaria",
        "quantidade": 10,
        "preco_unitario": 3,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Elaine",
        "produto": "Monitor",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 900,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 3),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Fabio",
        "produto": "Mochila",
        "categoria": "Acessórios",
        "quantidade": 2,
        "preco_unitario": 80,
        "cidade": "Jacarezinho",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Boleto"
    },
    {
        "cliente": "Gabriela",
        "produto": "Livro",
        "categoria": "Livros",
        "quantidade": 3,
        "preco_unitario": 40,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 4),
        "forma_pagamento": "Pix"
    },
    {
        "cliente": "Henrique",
        "produto": "Fone",
        "categoria": "Informática",
        "quantidade": 2,
        "preco_unitario": 150,
        "cidade": "Assis",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Cartão"
    },
    {
        "cliente": "Isabela",
        "produto": "Agenda",
        "categoria": "Papelaria",
        "quantidade": 4,
        "preco_unitario": 20,
        "cidade": "Salto Grande",
        "data": datetime(2026, 3, 5),
        "forma_pagamento": "Dinheiro"
    },
    {
        "cliente": "João",
        "produto": "Webcam",
        "categoria": "Informática",
        "quantidade": 1,
        "preco_unitario": 250,
        "cidade": "Ourinhos",
        "data": datetime(2026, 3, 6),
        "forma_pagamento": "Pix"
    }
]

In [5]:
colecao.insert_many(dados)

InsertManyResult([ObjectId('69c32c1fe722fbb2a7ea2aa3'), ObjectId('69c32c1fe722fbb2a7ea2aa4'), ObjectId('69c32c1fe722fbb2a7ea2aa5'), ObjectId('69c32c1fe722fbb2a7ea2aa6'), ObjectId('69c32c1fe722fbb2a7ea2aa7'), ObjectId('69c32c1fe722fbb2a7ea2aa8'), ObjectId('69c32c1fe722fbb2a7ea2aa9'), ObjectId('69c32c1fe722fbb2a7ea2aaa'), ObjectId('69c32c1fe722fbb2a7ea2aab'), ObjectId('69c32c1fe722fbb2a7ea2aac')], acknowledged=True)

In [6]:
dado_exemplo = list(colecao.find({'cliente' : 'Bruno'}))
display(dado_exemplo)

[{'_id': ObjectId('69c3184cbbff0af679f555f4'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa4'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'}]

In [7]:
dados_mongo = list(colecao.find({
    'preco_unitario' : {'$gte' : 100, '$lte' : 300}
}))

display(dados_mongo)

[{'_id': ObjectId('69c3184cbbff0af679f555f4'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3184cbbff0af679f555fa'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184cbbff0af679f555fc'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa4'),
  'cliente': 'Bruno',
  'produto': 'Teclado',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 120,
  'cidade': 'Jacarezinho',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aaa'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aac'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [8]:
dados_cidade = list(colecao.find({
    'cidade' : {'$in' : ['Ourinhos', 'Assis']}
}))
display(dados_cidade)

[{'_id': ObjectId('69c3184cbbff0af679f555f3'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184cbbff0af679f555f5'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c3184cbbff0af679f555f7'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184cbbff0af679f555f9'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c3184cbbff0af679f555fa'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c3184cbbff0af679f555fc'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa3'),
  'cliente': 'Ana',
  'produto': 'Mouse',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 50,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa5'),
  'cliente': 'Carla',
  'produto': 'Caderno',
  'categoria': 'Papelaria',
  'quantidade': 5,
  'preco_unitario': 15,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa7'),
  'cliente': 'Elaine',
  'produto': 'Monitor',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aa9'),
  'cliente': 'Gabriela',
  'produto': 'Livro',
  'categoria': 'Livros',
  'quantidade': 3,
  'preco_unitario': 40,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aaa'),
  'cliente': 'Henrique',
  'produto': 'Fone',
  'categoria': 'Informática',
  'quantidade': 2,
  'preco_unitario': 150,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69c32c1fe722fbb2a7ea2aac'),
  'cliente': 'João',
  'produto': 'Webcam',
  'categoria': 'Informática',
  'quantidade': 1,
  'preco_unitario': 250,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'}]

In [9]:
df = pd.DataFrame(dados_cidade)
df

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento
0,69c3184cbbff0af679f555f3,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
1,69c3184cbbff0af679f555f5,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
2,69c3184cbbff0af679f555f7,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
3,69c3184cbbff0af679f555f9,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
4,69c3184cbbff0af679f555fa,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
5,69c3184cbbff0af679f555fc,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix
6,69c32c1fe722fbb2a7ea2aa3,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão
7,69c32c1fe722fbb2a7ea2aa5,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro
8,69c32c1fe722fbb2a7ea2aa7,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão
9,69c32c1fe722fbb2a7ea2aa9,Gabriela,Livro,Livros,3,40,Ourinhos,2026-03-04,Pix
10,69c32c1fe722fbb2a7ea2aaa,Henrique,Fone,Informática,2,150,Assis,2026-03-05,Cartão
11,69c32c1fe722fbb2a7ea2aac,João,Webcam,Informática,1,250,Ourinhos,2026-03-06,Pix

In [10]:
df.isnull().sum()

_id                0
cliente            0
produto            0
categoria          0
quantidade         0
preco_unitario     0
cidade             0
data               0
forma_pagamento    0
dtype: int64

In [11]:
df['valor_total'] = df['quantidade'] * df['preco_unitario']
df.head(3)

,_id,cliente,produto,categoria,quantidade,preco_unitario,cidade,data,forma_pagamento,valor_total
0,69c3184cbbff0af679f555f3,Ana,Mouse,Informática,2,50,Ourinhos,2026-03-01,Cartão,100
1,69c3184cbbff0af679f555f5,Carla,Caderno,Papelaria,5,15,Ourinhos,2026-03-02,Dinheiro,75
2,69c3184cbbff0af679f555f7,Elaine,Monitor,Informática,1,900,Ourinhos,2026-03-03,Cartão,900

In [12]:
faturamento = df['valor_total'].sum()
print("Faturamento Total: ", faturamento)

Faturamento Total:  3490

In [13]:
faturamento_categoria = df.groupby('categoria')['valor_total'].sum().sort_values(ascending=False)
faturamento_categoria

categoria
Informática    3100
Livros          240
Papelaria       150
Name: valor_total, dtype: int64

In [14]:
faturamento_produto = df.groupby('produto')['valor_total'].sum().sort_values(ascending=False)
faturamento_produto

produto
Monitor    1800
Fone        600
Webcam      500
Livro       240
Mouse       200
Caderno     150
Name: valor_total, dtype: int64

In [15]:
vendas_por_cidade = df['cidade'].value_counts()
vendas_por_cidade

cidade
Ourinhos    10
Assis        2
Name: count, dtype: int64

In [16]:
media_valor_vendas = df['valor_total'].mean()
print(f"Média do valor das vendas: {media_valor_vendas:.2f}")

Média do valor das vendas: 290.83

In [17]:
produto_top = df.groupby('produto')['valor_total'].sum().idxmax()
produto_top

'Monitor'

In [18]:
cidade_top = df['cidade'].value_counts().idxmax()
cidade_top

'Ourinhos'

In [19]:
relatorio = {
    'data_geracao' : datetime.now(),
    'faturamento_total': float(faturamento),
    'faturamento_categoria' : faturamento_categoria.to_dict(),
    'produto_top': produto_top,
    'cidade_top' : cidade_top
}

display(relatorio)

{'data_geracao': datetime.datetime(2026, 3, 25, 0, 36, 30, 408316),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}

In [20]:
colecao_relatorios = db['relatorios']
colecao_relatorios.insert_one(relatorio)

InsertOneResult(ObjectId('69c32e53e722fbb2a7ea2aad'), acknowledged=True)

In [21]:
for r in colecao_relatorios.find():
    display(r)

{'_id': ObjectId('69c32e53e722fbb2a7ea2aad'),
 'data_geracao': datetime.datetime(2026, 3, 25, 0, 36, 30, 408000),
 'faturamento_total': 3490.0,
 'faturamento_categoria': {'Informática': 3100,
  'Livros': 240,
  'Papelaria': 150},
 'produto_top': 'Monitor',
 'cidade_top': 'Ourinhos'}