In [1]:
from pymongo import MongoClient
import pandas as pd
from datetime import datetime

In [3]:
client = MongoClient("mongodb://root:rootpass@localhost:27017")
print(client.server_info()['version'])

8.2.6

In [ ]:
db = client["clinica_veterinaria"]
colecao_atendimentos = db["atendimentos"]
colecao_relatorios = db["relatorios"]

In [5]:
dados = [
{"tutor":"Ana","animal":"Cachorro","nome_pet":"Rex1","servico":"Consulta","valor":120,"cidade":"Assis","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Bruno","animal":"Gato","nome_pet":"Mimi2","servico":"Vacinação","valor":95,"cidade":"Assis","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Carlos","animal":"Cachorro","nome_pet":"Thor3","servico":"Banho","valor":60,"cidade":"Assis","data":datetime(2026,3,3),"forma_pagamento":"Dinheiro"},
{"tutor":"Daniela","animal":"Ave","nome_pet":"Piu4","servico":"Exame","valor":180,"cidade":"Assis","data":datetime(2026,3,4),"forma_pagamento":"Cartão"},
{"tutor":"Eduardo","animal":"Gato","nome_pet":"Luna5","servico":"Consulta","valor":130,"cidade":"Assis","data":datetime(2026,3,5),"forma_pagamento":"Pix"},
{"tutor":"Fernanda","animal":"Cachorro","nome_pet":"Bob6","servico":"Vacinação","valor":90,"cidade":"Assis","data":datetime(2026,3,6),"forma_pagamento":"Dinheiro"},
{"tutor":"Gabriel","animal":"Coelho","nome_pet":"Pompom7","servico":"Consulta","valor":110,"cidade":"Assis","data":datetime(2026,3,7),"forma_pagamento":"Pix"},
{"tutor":"Helena","animal":"Cachorro","nome_pet":"Mel8","servico":"Cirurgia","valor":820,"cidade":"Assis","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Igor","animal":"Gato","nome_pet":"Simba9","servico":"Banho","valor":55,"cidade":"Assis","data":datetime(2026,3,9),"forma_pagamento":"Cartão"},
{"tutor":"Juliana","animal":"Cachorro","nome_pet":"Nina10","servico":"Consulta","valor":125,"cidade":"Assis","data":datetime(2026,3,10),"forma_pagamento":"Pix"},
{"tutor":"Lucas","animal":"Ave","nome_pet":"Sky11","servico":"Exame","valor":200,"cidade":"Assis","data":datetime(2026,3,11),"forma_pagamento":"Cartão"},
{"tutor":"Mariana","animal":"Gato","nome_pet":"Lili12","servico":"Consulta","valor":135,"cidade":"Assis","data":datetime(2026,3,12),"forma_pagamento":"Pix"},
{"tutor":"Nicolas","animal":"Cachorro","nome_pet":"Bolt13","servico":"Vacinação","valor":100,"cidade":"Assis","data":datetime(2026,3,13),"forma_pagamento":"Dinheiro"},
{"tutor":"Patricia","animal":"Cachorro","nome_pet":"Max14","servico":"Consulta","valor":140,"cidade":"Ourinhos","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Rafael","animal":"Gato","nome_pet":"Mia15","servico":"Banho","valor":65,"cidade":"Ourinhos","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Sofia","animal":"Cachorro","nome_pet":"Luna16","servico":"Cirurgia","valor":900,"cidade":"Ourinhos","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Thiago","animal":"Ave","nome_pet":"Blue17","servico":"Exame","valor":170,"cidade":"Ourinhos","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Vanessa","animal":"Gato","nome_pet":"Nino18","servico":"Consulta","valor":125,"cidade":"Ourinhos","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"William","animal":"Cachorro","nome_pet":"Thor19","servico":"Vacinação","valor":95,"cidade":"Ourinhos","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Beatriz","animal":"Coelho","nome_pet":"Fluffy20","servico":"Consulta","valor":115,"cidade":"Ourinhos","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Caio","animal":"Cachorro","nome_pet":"Spike21","servico":"Banho","valor":70,"cidade":"Ourinhos","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Diego","animal":"Gato","nome_pet":"Tom22","servico":"Consulta","valor":135,"cidade":"Ourinhos","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Elisa","animal":"Cachorro","nome_pet":"Mel23","servico":"Exame","valor":210,"cidade":"Ourinhos","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Felipe","animal":"Ave","nome_pet":"Kiwi24","servico":"Consulta","valor":120,"cidade":"Ourinhos","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Gisele","animal":"Gato","nome_pet":"Nina25","servico":"Vacinação","valor":85,"cidade":"Ourinhos","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Hugo","animal":"Cachorro","nome_pet":"Rex26","servico":"Consulta","valor":150,"cidade":"Ourinhos","data":datetime(2026,3,13),"forma_pagamento":"Cartão"},
{"tutor":"Iris","animal":"Cachorro","nome_pet":"Bob27","servico":"Consulta","valor":110,"cidade":"Pompeia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Joao","animal":"Gato","nome_pet":"Luna28","servico":"Banho","valor":60,"cidade":"Pompeia","data":datetime(2026,3,2),"forma_pagamento":"Dinheiro"},
{"tutor":"Karen","animal":"Cachorro","nome_pet":"Thor29","servico":"Cirurgia","valor":780,"cidade":"Pompeia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Leo","animal":"Ave","nome_pet":"Sky30","servico":"Exame","valor":160,"cidade":"Pompeia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Marta","animal":"Gato","nome_pet":"Mimi31","servico":"Consulta","valor":120,"cidade":"Pompeia","data":datetime(2026,3,5),"forma_pagamento":"Cartão"},
{"tutor":"Nelson","animal":"Cachorro","nome_pet":"Max32","servico":"Vacinação","valor":90,"cidade":"Pompeia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Olga","animal":"Coelho","nome_pet":"Pompom33","servico":"Consulta","valor":105,"cidade":"Pompeia","data":datetime(2026,3,7),"forma_pagamento":"Dinheiro"},
{"tutor":"Paulo","animal":"Cachorro","nome_pet":"Bolt34","servico":"Banho","valor":75,"cidade":"Pompeia","data":datetime(2026,3,8),"forma_pagamento":"Cartão"},
{"tutor":"Quezia","animal":"Gato","nome_pet":"Simba35","servico":"Consulta","valor":130,"cidade":"Pompeia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Renato","animal":"Cachorro","nome_pet":"Nina36","servico":"Exame","valor":190,"cidade":"Pompeia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Sara","animal":"Ave","nome_pet":"Blue37","servico":"Consulta","valor":115,"cidade":"Pompeia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Tiago","animal":"Gato","nome_pet":"Lili38","servico":"Vacinação","valor":85,"cidade":"Pompeia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
{"tutor":"Ursula","animal":"Cachorro","nome_pet":"Rex39","servico":"Consulta","valor":145,"cidade":"Marilia","data":datetime(2026,3,1),"forma_pagamento":"Pix"},
{"tutor":"Vitor","animal":"Gato","nome_pet":"Mia40","servico":"Banho","valor":70,"cidade":"Marilia","data":datetime(2026,3,2),"forma_pagamento":"Cartão"},
{"tutor":"Wesley","animal":"Cachorro","nome_pet":"Thor41","servico":"Cirurgia","valor":870,"cidade":"Marilia","data":datetime(2026,3,3),"forma_pagamento":"Cartão"},
{"tutor":"Xuxa","animal":"Ave","nome_pet":"Piu42","servico":"Exame","valor":175,"cidade":"Marilia","data":datetime(2026,3,4),"forma_pagamento":"Pix"},
{"tutor":"Yara","animal":"Gato","nome_pet":"Luna43","servico":"Consulta","valor":135,"cidade":"Marilia","data":datetime(2026,3,5),"forma_pagamento":"Dinheiro"},
{"tutor":"Zeca","animal":"Cachorro","nome_pet":"Bob44","servico":"Vacinação","valor":100,"cidade":"Marilia","data":datetime(2026,3,6),"forma_pagamento":"Pix"},
{"tutor":"Aline","animal":"Coelho","nome_pet":"Fluffy45","servico":"Consulta","valor":120,"cidade":"Marilia","data":datetime(2026,3,7),"forma_pagamento":"Cartão"},
{"tutor":"Bruna","animal":"Cachorro","nome_pet":"Spike46","servico":"Banho","valor":80,"cidade":"Marilia","data":datetime(2026,3,8),"forma_pagamento":"Dinheiro"},
{"tutor":"Cesar","animal":"Gato","nome_pet":"Tom47","servico":"Consulta","valor":140,"cidade":"Marilia","data":datetime(2026,3,9),"forma_pagamento":"Pix"},
{"tutor":"Dora","animal":"Cachorro","nome_pet":"Mel48","servico":"Exame","valor":220,"cidade":"Marilia","data":datetime(2026,3,10),"forma_pagamento":"Cartão"},
{"tutor":"Enzo","animal":"Ave","nome_pet":"Kiwi49","servico":"Consulta","valor":130,"cidade":"Marilia","data":datetime(2026,3,11),"forma_pagamento":"Pix"},
{"tutor":"Fabio","animal":"Gato","nome_pet":"Nina50","servico":"Vacinação","valor":90,"cidade":"Marilia","data":datetime(2026,3,12),"forma_pagamento":"Dinheiro"},
]

In [6]:
colecao_atendimentos.insert_many(dados)

InsertManyResult([ObjectId('69d1465017446bcb56344fa1'), ObjectId('69d1465017446bcb56344fa2'), ObjectId('69d1465017446bcb56344fa3'), ObjectId('69d1465017446bcb56344fa4'), ObjectId('69d1465017446bcb56344fa5'), ObjectId('69d1465017446bcb56344fa6'), ObjectId('69d1465017446bcb56344fa7'), ObjectId('69d1465017446bcb56344fa8'), ObjectId('69d1465017446bcb56344fa9'), ObjectId('69d1465017446bcb56344faa'), ObjectId('69d1465017446bcb56344fab'), ObjectId('69d1465017446bcb56344fac'), ObjectId('69d1465017446bcb56344fad'), ObjectId('69d1465017446bcb56344fae'), ObjectId('69d1465017446bcb56344faf'), ObjectId('69d1465017446bcb56344fb0'), ObjectId('69d1465017446bcb56344fb1'), ObjectId('69d1465017446bcb56344fb2'), ObjectId('69d1465017446bcb56344fb3'), ObjectId('69d1465017446bcb56344fb4'), ObjectId('69d1465017446bcb56344fb5'), ObjectId('69d1465017446bcb56344fb6'), ObjectId('69d1465017446bcb56344fb7'), ObjectId('69d1465017446bcb56344fb8'), ObjectId('69d1465017446bcb56344fb9'), ObjectId('69d1465017446bcb56344fba'), ObjectId('69d1465017446bcb56344fbb'), ObjectId('69d1465017446bcb56344fbc'), ObjectId('69d1465017446bcb56344fbd'), ObjectId('69d1465017446bcb56344fbe'), ObjectId('69d1465017446bcb56344fbf'), ObjectId('69d1465017446bcb56344fc0'), ObjectId('69d1465017446bcb56344fc1'), ObjectId('69d1465017446bcb56344fc2'), ObjectId('69d1465017446bcb56344fc3'), ObjectId('69d1465017446bcb56344fc4'), ObjectId('69d1465017446bcb56344fc5'), ObjectId('69d1465017446bcb56344fc6'), ObjectId('69d1465017446bcb56344fc7'), ObjectId('69d1465017446bcb56344fc8'), ObjectId('69d1465017446bcb56344fc9'), ObjectId('69d1465017446bcb56344fca'), ObjectId('69d1465017446bcb56344fcb'), ObjectId('69d1465017446bcb56344fcc'), ObjectId('69d1465017446bcb56344fcd'), ObjectId('69d1465017446bcb56344fce'), ObjectId('69d1465017446bcb56344fcf'), ObjectId('69d1465017446bcb56344fd0'), ObjectId('69d1465017446bcb56344fd1'), ObjectId('69d1465017446bcb56344fd2')], acknowledged=True)

In [7]:
ex2 = list(colecao_atendimentos.find({
    'valor': {'$gte': 90, '$lte': 200}
}))

display(ex2)

[{'_id': ObjectId('69d1465017446bcb56344fa1'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fa2'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fa4'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fa5'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fa6'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fa7'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344faa'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fab'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fac'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fad'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fae'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb1'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb2'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fb3'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb4'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fb6'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb8'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fba'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fbb'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fbe'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fbf'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc0'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc1'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fc3'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc4'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc5'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc7'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fca'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fcb'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fcc'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fcd'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fcf'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fd1'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fd2'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [12]:
ex3 = list(colecao_atendimentos.find({
    'cidade': {'$in': ['Assis', 'Ourinhos', 'Pompeia', 'Marilia']}
}))
display(ex3)

[{'_id': ObjectId('69d1465017446bcb56344fa1'),
  'tutor': 'Ana',
  'animal': 'Cachorro',
  'nome_pet': 'Rex1',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fa2'),
  'tutor': 'Bruno',
  'animal': 'Gato',
  'nome_pet': 'Mimi2',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fa3'),
  'tutor': 'Carlos',
  'animal': 'Cachorro',
  'nome_pet': 'Thor3',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fa4'),
  'tutor': 'Daniela',
  'animal': 'Ave',
  'nome_pet': 'Piu4',
  'servico': 'Exame',
  'valor': 180,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fa5'),
  'tutor': 'Eduardo',
  'animal': 'Gato',
  'nome_pet': 'Luna5',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fa6'),
  'tutor': 'Fernanda',
  'animal': 'Cachorro',
  'nome_pet': 'Bob6',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fa7'),
  'tutor': 'Gabriel',
  'animal': 'Coelho',
  'nome_pet': 'Pompom7',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fa8'),
  'tutor': 'Helena',
  'animal': 'Cachorro',
  'nome_pet': 'Mel8',
  'servico': 'Cirurgia',
  'valor': 820,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fa9'),
  'tutor': 'Igor',
  'animal': 'Gato',
  'nome_pet': 'Simba9',
  'servico': 'Banho',
  'valor': 55,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344faa'),
  'tutor': 'Juliana',
  'animal': 'Cachorro',
  'nome_pet': 'Nina10',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fab'),
  'tutor': 'Lucas',
  'animal': 'Ave',
  'nome_pet': 'Sky11',
  'servico': 'Exame',
  'valor': 200,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fac'),
  'tutor': 'Mariana',
  'animal': 'Gato',
  'nome_pet': 'Lili12',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fad'),
  'tutor': 'Nicolas',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt13',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Assis',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fae'),
  'tutor': 'Patricia',
  'animal': 'Cachorro',
  'nome_pet': 'Max14',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344faf'),
  'tutor': 'Rafael',
  'animal': 'Gato',
  'nome_pet': 'Mia15',
  'servico': 'Banho',
  'valor': 65,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fb0'),
  'tutor': 'Sofia',
  'animal': 'Cachorro',
  'nome_pet': 'Luna16',
  'servico': 'Cirurgia',
  'valor': 900,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fb1'),
  'tutor': 'Thiago',
  'animal': 'Ave',
  'nome_pet': 'Blue17',
  'servico': 'Exame',
  'valor': 170,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb2'),
  'tutor': 'Vanessa',
  'animal': 'Gato',
  'nome_pet': 'Nino18',
  'servico': 'Consulta',
  'valor': 125,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fb3'),
  'tutor': 'William',
  'animal': 'Cachorro',
  'nome_pet': 'Thor19',
  'servico': 'Vacinação',
  'valor': 95,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb4'),
  'tutor': 'Beatriz',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy20',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fb5'),
  'tutor': 'Caio',
  'animal': 'Cachorro',
  'nome_pet': 'Spike21',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fb6'),
  'tutor': 'Diego',
  'animal': 'Gato',
  'nome_pet': 'Tom22',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb7'),
  'tutor': 'Elisa',
  'animal': 'Cachorro',
  'nome_pet': 'Mel23',
  'servico': 'Exame',
  'valor': 210,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fb8'),
  'tutor': 'Felipe',
  'animal': 'Ave',
  'nome_pet': 'Kiwi24',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fb9'),
  'tutor': 'Gisele',
  'animal': 'Gato',
  'nome_pet': 'Nina25',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fba'),
  'tutor': 'Hugo',
  'animal': 'Cachorro',
  'nome_pet': 'Rex26',
  'servico': 'Consulta',
  'valor': 150,
  'cidade': 'Ourinhos',
  'data': datetime.datetime(2026, 3, 13, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fbb'),
  'tutor': 'Iris',
  'animal': 'Cachorro',
  'nome_pet': 'Bob27',
  'servico': 'Consulta',
  'valor': 110,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fbc'),
  'tutor': 'Joao',
  'animal': 'Gato',
  'nome_pet': 'Luna28',
  'servico': 'Banho',
  'valor': 60,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fbd'),
  'tutor': 'Karen',
  'animal': 'Cachorro',
  'nome_pet': 'Thor29',
  'servico': 'Cirurgia',
  'valor': 780,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fbe'),
  'tutor': 'Leo',
  'animal': 'Ave',
  'nome_pet': 'Sky30',
  'servico': 'Exame',
  'valor': 160,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fbf'),
  'tutor': 'Marta',
  'animal': 'Gato',
  'nome_pet': 'Mimi31',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc0'),
  'tutor': 'Nelson',
  'animal': 'Cachorro',
  'nome_pet': 'Max32',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc1'),
  'tutor': 'Olga',
  'animal': 'Coelho',
  'nome_pet': 'Pompom33',
  'servico': 'Consulta',
  'valor': 105,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fc2'),
  'tutor': 'Paulo',
  'animal': 'Cachorro',
  'nome_pet': 'Bolt34',
  'servico': 'Banho',
  'valor': 75,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc3'),
  'tutor': 'Quezia',
  'animal': 'Gato',
  'nome_pet': 'Simba35',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc4'),
  'tutor': 'Renato',
  'animal': 'Cachorro',
  'nome_pet': 'Nina36',
  'servico': 'Exame',
  'valor': 190,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc5'),
  'tutor': 'Sara',
  'animal': 'Ave',
  'nome_pet': 'Blue37',
  'servico': 'Consulta',
  'valor': 115,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc6'),
  'tutor': 'Tiago',
  'animal': 'Gato',
  'nome_pet': 'Lili38',
  'servico': 'Vacinação',
  'valor': 85,
  'cidade': 'Pompeia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fc7'),
  'tutor': 'Ursula',
  'animal': 'Cachorro',
  'nome_pet': 'Rex39',
  'servico': 'Consulta',
  'valor': 145,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 1, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fc8'),
  'tutor': 'Vitor',
  'animal': 'Gato',
  'nome_pet': 'Mia40',
  'servico': 'Banho',
  'valor': 70,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 2, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fc9'),
  'tutor': 'Wesley',
  'animal': 'Cachorro',
  'nome_pet': 'Thor41',
  'servico': 'Cirurgia',
  'valor': 870,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 3, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fca'),
  'tutor': 'Xuxa',
  'animal': 'Ave',
  'nome_pet': 'Piu42',
  'servico': 'Exame',
  'valor': 175,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 4, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fcb'),
  'tutor': 'Yara',
  'animal': 'Gato',
  'nome_pet': 'Luna43',
  'servico': 'Consulta',
  'valor': 135,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 5, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fcc'),
  'tutor': 'Zeca',
  'animal': 'Cachorro',
  'nome_pet': 'Bob44',
  'servico': 'Vacinação',
  'valor': 100,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 6, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fcd'),
  'tutor': 'Aline',
  'animal': 'Coelho',
  'nome_pet': 'Fluffy45',
  'servico': 'Consulta',
  'valor': 120,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 7, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fce'),
  'tutor': 'Bruna',
  'animal': 'Cachorro',
  'nome_pet': 'Spike46',
  'servico': 'Banho',
  'valor': 80,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 8, 0, 0),
  'forma_pagamento': 'Dinheiro'},
 {'_id': ObjectId('69d1465017446bcb56344fcf'),
  'tutor': 'Cesar',
  'animal': 'Gato',
  'nome_pet': 'Tom47',
  'servico': 'Consulta',
  'valor': 140,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 9, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fd0'),
  'tutor': 'Dora',
  'animal': 'Cachorro',
  'nome_pet': 'Mel48',
  'servico': 'Exame',
  'valor': 220,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 10, 0, 0),
  'forma_pagamento': 'Cartão'},
 {'_id': ObjectId('69d1465017446bcb56344fd1'),
  'tutor': 'Enzo',
  'animal': 'Ave',
  'nome_pet': 'Kiwi49',
  'servico': 'Consulta',
  'valor': 130,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 11, 0, 0),
  'forma_pagamento': 'Pix'},
 {'_id': ObjectId('69d1465017446bcb56344fd2'),
  'tutor': 'Fabio',
  'animal': 'Gato',
  'nome_pet': 'Nina50',
  'servico': 'Vacinação',
  'valor': 90,
  'cidade': 'Marilia',
  'data': datetime.datetime(2026, 3, 12, 0, 0),
  'forma_pagamento': 'Dinheiro'}]

In [10]:
df = pd.DataFrame(ex2)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69d1465017446bcb56344fa1,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69d1465017446bcb56344fa2,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69d1465017446bcb56344fa4,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
3,69d1465017446bcb56344fa5,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
4,69d1465017446bcb56344fa6,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
5,69d1465017446bcb56344fa7,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
6,69d1465017446bcb56344faa,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
7,69d1465017446bcb56344fab,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
8,69d1465017446bcb56344fac,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
9,69d1465017446bcb56344fad,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
10,69d1465017446bcb56344fae,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
11,69d1465017446bcb56344fb1,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
12,69d1465017446bcb56344fb2,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
13,69d1465017446bcb56344fb3,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
14,69d1465017446bcb56344fb4,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
15,69d1465017446bcb56344fb6,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
16,69d1465017446bcb56344fb8,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
17,69d1465017446bcb56344fba,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
18,69d1465017446bcb56344fbb,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
19,69d1465017446bcb56344fbe,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
20,69d1465017446bcb56344fbf,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
21,69d1465017446bcb56344fc0,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
22,69d1465017446bcb56344fc1,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
23,69d1465017446bcb56344fc3,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
24,69d1465017446bcb56344fc4,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
25,69d1465017446bcb56344fc5,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
26,69d1465017446bcb56344fc7,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
27,69d1465017446bcb56344fca,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
28,69d1465017446bcb56344fcb,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
29,69d1465017446bcb56344fcc,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
30,69d1465017446bcb56344fcd,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
31,69d1465017446bcb56344fcf,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
32,69d1465017446bcb56344fd1,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
33,69d1465017446bcb56344fd2,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [13]:
df = pd.DataFrame(ex3)
df

,_id,tutor,animal,nome_pet,servico,valor,cidade,data,forma_pagamento
0,69d1465017446bcb56344fa1,Ana,Cachorro,Rex1,Consulta,120,Assis,2026-03-01,Pix
1,69d1465017446bcb56344fa2,Bruno,Gato,Mimi2,Vacinação,95,Assis,2026-03-02,Cartão
2,69d1465017446bcb56344fa3,Carlos,Cachorro,Thor3,Banho,60,Assis,2026-03-03,Dinheiro
3,69d1465017446bcb56344fa4,Daniela,Ave,Piu4,Exame,180,Assis,2026-03-04,Cartão
4,69d1465017446bcb56344fa5,Eduardo,Gato,Luna5,Consulta,130,Assis,2026-03-05,Pix
5,69d1465017446bcb56344fa6,Fernanda,Cachorro,Bob6,Vacinação,90,Assis,2026-03-06,Dinheiro
6,69d1465017446bcb56344fa7,Gabriel,Coelho,Pompom7,Consulta,110,Assis,2026-03-07,Pix
7,69d1465017446bcb56344fa8,Helena,Cachorro,Mel8,Cirurgia,820,Assis,2026-03-08,Cartão
8,69d1465017446bcb56344fa9,Igor,Gato,Simba9,Banho,55,Assis,2026-03-09,Cartão
9,69d1465017446bcb56344faa,Juliana,Cachorro,Nina10,Consulta,125,Assis,2026-03-10,Pix
10,69d1465017446bcb56344fab,Lucas,Ave,Sky11,Exame,200,Assis,2026-03-11,Cartão
11,69d1465017446bcb56344fac,Mariana,Gato,Lili12,Consulta,135,Assis,2026-03-12,Pix
12,69d1465017446bcb56344fad,Nicolas,Cachorro,Bolt13,Vacinação,100,Assis,2026-03-13,Dinheiro
13,69d1465017446bcb56344fae,Patricia,Cachorro,Max14,Consulta,140,Ourinhos,2026-03-01,Pix
14,69d1465017446bcb56344faf,Rafael,Gato,Mia15,Banho,65,Ourinhos,2026-03-02,Cartão
15,69d1465017446bcb56344fb0,Sofia,Cachorro,Luna16,Cirurgia,900,Ourinhos,2026-03-03,Cartão
16,69d1465017446bcb56344fb1,Thiago,Ave,Blue17,Exame,170,Ourinhos,2026-03-04,Pix
17,69d1465017446bcb56344fb2,Vanessa,Gato,Nino18,Consulta,125,Ourinhos,2026-03-05,Dinheiro
18,69d1465017446bcb56344fb3,William,Cachorro,Thor19,Vacinação,95,Ourinhos,2026-03-06,Pix
19,69d1465017446bcb56344fb4,Beatriz,Coelho,Fluffy20,Consulta,115,Ourinhos,2026-03-07,Cartão
20,69d1465017446bcb56344fb5,Caio,Cachorro,Spike21,Banho,70,Ourinhos,2026-03-08,Dinheiro
21,69d1465017446bcb56344fb6,Diego,Gato,Tom22,Consulta,135,Ourinhos,2026-03-09,Pix
22,69d1465017446bcb56344fb7,Elisa,Cachorro,Mel23,Exame,210,Ourinhos,2026-03-10,Cartão
23,69d1465017446bcb56344fb8,Felipe,Ave,Kiwi24,Consulta,120,Ourinhos,2026-03-11,Pix
24,69d1465017446bcb56344fb9,Gisele,Gato,Nina25,Vacinação,85,Ourinhos,2026-03-12,Dinheiro
25,69d1465017446bcb56344fba,Hugo,Cachorro,Rex26,Consulta,150,Ourinhos,2026-03-13,Cartão
26,69d1465017446bcb56344fbb,Iris,Cachorro,Bob27,Consulta,110,Pompeia,2026-03-01,Pix
27,69d1465017446bcb56344fbc,Joao,Gato,Luna28,Banho,60,Pompeia,2026-03-02,Dinheiro
28,69d1465017446bcb56344fbd,Karen,Cachorro,Thor29,Cirurgia,780,Pompeia,2026-03-03,Cartão
29,69d1465017446bcb56344fbe,Leo,Ave,Sky30,Exame,160,Pompeia,2026-03-04,Pix
30,69d1465017446bcb56344fbf,Marta,Gato,Mimi31,Consulta,120,Pompeia,2026-03-05,Cartão
31,69d1465017446bcb56344fc0,Nelson,Cachorro,Max32,Vacinação,90,Pompeia,2026-03-06,Pix
32,69d1465017446bcb56344fc1,Olga,Coelho,Pompom33,Consulta,105,Pompeia,2026-03-07,Dinheiro
33,69d1465017446bcb56344fc2,Paulo,Cachorro,Bolt34,Banho,75,Pompeia,2026-03-08,Cartão
34,69d1465017446bcb56344fc3,Quezia,Gato,Simba35,Consulta,130,Pompeia,2026-03-09,Pix
35,69d1465017446bcb56344fc4,Renato,Cachorro,Nina36,Exame,190,Pompeia,2026-03-10,Cartão
36,69d1465017446bcb56344fc5,Sara,Ave,Blue37,Consulta,115,Pompeia,2026-03-11,Pix
37,69d1465017446bcb56344fc6,Tiago,Gato,Lili38,Vacinação,85,Pompeia,2026-03-12,Dinheiro
38,69d1465017446bcb56344fc7,Ursula,Cachorro,Rex39,Consulta,145,Marilia,2026-03-01,Pix
39,69d1465017446bcb56344fc8,Vitor,Gato,Mia40,Banho,70,Marilia,2026-03-02,Cartão
40,69d1465017446bcb56344fc9,Wesley,Cachorro,Thor41,Cirurgia,870,Marilia,2026-03-03,Cartão
41,69d1465017446bcb56344fca,Xuxa,Ave,Piu42,Exame,175,Marilia,2026-03-04,Pix
42,69d1465017446bcb56344fcb,Yara,Gato,Luna43,Consulta,135,Marilia,2026-03-05,Dinheiro
43,69d1465017446bcb56344fcc,Zeca,Cachorro,Bob44,Vacinação,100,Marilia,2026-03-06,Pix
44,69d1465017446bcb56344fcd,Aline,Coelho,Fluffy45,Consulta,120,Marilia,2026-03-07,Cartão
45,69d1465017446bcb56344fce,Bruna,Cachorro,Spike46,Banho,80,Marilia,2026-03-08,Dinheiro
46,69d1465017446bcb56344fcf,Cesar,Gato,Tom47,Consulta,140,Marilia,2026-03-09,Pix
47,69d1465017446bcb56344fd0,Dora,Cachorro,Mel48,Exame,220,Marilia,2026-03-10,Cartão
48,69d1465017446bcb56344fd1,Enzo,Ave,Kiwi49,Consulta,130,Marilia,2026-03-11,Pix
49,69d1465017446bcb56344fd2,Fabio,Gato,Nina50,Vacinação,90,Marilia,2026-03-12,Dinheiro

In [14]:
df.isnull().sum()

_id                0
tutor              0
animal             0
nome_pet           0
servico            0
valor              0
cidade             0
data               0
forma_pagamento    0
dtype: int64